config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get 'user/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
=begin

before it was 
get 'static_pages/help'
now we change to the above 

after writing the above , for each of help about and contact we get _path and _url 

help_path -> '/help'
help_url  -> 'http://www.example.com/help'
  
=end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    	@micropost = current_user.microposts.build 
    	@feed_items = current_user.feed.page(params[:page]).per(15)
    end
  end

  def help
  end

  def about 
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def full_title(page_title = '')
		base_title = "Ruby on Rails PostIt App"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
This is a web application developed with Ruby on Rails.
It consists of a full rails authentication using sessions and cookies. Users can post and follow other users.
COMPLETED :
<ul>
<li>Sign up</li>
<li>Sessions, Logging in, Logging out, Remember me</li>
<li>Updating profile</li>
<li>Showing all Users</li>
<li>Authorization, Deleting Users</li>
<li>Account Activation, Password Reset, Sending Emails</li>
<li>User's posts</li>
<li>Following other Users</li>
</ul>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  This is the contact page for the Post It Application
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
 This is the help page for the Post It Application 
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

<% else %>

  <!--% provide(:title, "Home") %-->
  <div class="center jumbotron">
    <h1>Welcome to the Post It App</h1>

    <h2>
      Create your account to start following other users <br>and see their posts !
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <!-- <%#= link_to image_tag("rails.jpg", alt: "Rails logo"),
              'http://rubyonrails.org/' %> -->

<% end %>